-- Lucy Mail Archive - archivio generale e classificazione AI
create table if not exists public.lucy_mail_archive (
  id bigint generated by default as identity primary key,
  gmail_message_id text not null unique,
  gmail_thread_id text,
  mittente text,
  destinatario_originale text,
  oggetto text,
  testo_completo text,
  data_mail timestamptz,
  cliente_id bigint,
  cliente_nome text,
  bookmaker text,
  gmail_labels text[] default '{}',
  categoria text default 'DA_ANALIZZARE',
  giudizio text default 'DA_ANALIZZARE',
  priorita text default 'media',
  confidenza numeric(5,2),
  tipo_offerta text,
  bonus_importo numeric(12,2),
  deposito_richiesto numeric(12,2),
  rollover text,
  scadenza timestamptz,
  condizioni text,
  motivazione_ai text,
  richiede_azione boolean default false,
  letta boolean default false,
  feedback_utente text,
  feedback_note text,
  analizzata_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lucy_mail_archive_data_idx on public.lucy_mail_archive (data_mail desc);
create index if not exists lucy_mail_archive_cliente_idx on public.lucy_mail_archive (cliente_nome);
create index if not exists lucy_mail_archive_bookmaker_idx on public.lucy_mail_archive (bookmaker);
create index if not exists lucy_mail_archive_giudizio_idx on public.lucy_mail_archive (giudizio);
create index if not exists lucy_mail_archive_categoria_idx on public.lucy_mail_archive (categoria);
create index if not exists lucy_mail_archive_priorita_idx on public.lucy_mail_archive (priorita);

alter table public.lucy_mail_archive enable row level security;

comment on table public.lucy_mail_archive is
'Archivio completo Lucy: tutte le email vengono salvate prima della classificazione AI; nessuna email viene eliminata in base al giudizio AI.';

-- Connessione Gmail centrale Lucy (token usati solo dal backend service-role)
create table if not exists public.lucy_gmail_connection (
  id smallint primary key default 1 check (id = 1),
  email text not null,
  access_token text,
  refresh_token text,
  token_expiry timestamptz,
  connected_at timestamptz,
  last_sync_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.lucy_gmail_connection enable row level security;
